import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const robotoCondensed = localFont({
  src: [
    {
      path: '../fonts/RobotoCondensed-VariableFont_wght.ttf',
      style: 'normal',
    },
    {
      path: '../fonts/RobotoCondensed-Italic-VariableFont_wght.ttf',
      style: 'italic',
    },
  ],
  display: 'swap',
  variable: '--font-roboto-condensed'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.className} antialiased bg-neutral-100`}
      >
        {children}
      </body>
    </html>
  );
}
